### ISSUE TITLE
[FR]Setting the properties of the list format to be exported to card

### ISSUE THREAD

**Issue by kazdonkai** [aarongilly/obsidian-semantic-canvas-plugin#1]
First, thank you for the great plugin.
Then I have a request regarding the list format that will be the cards on the canvas.
As you can see in the image, I often give multiple names to aliases. Then the aliases are also exported as cards.
This is a problem.
So, I would like to see a specification that alias names are not made into cards, or, more generally, I would like to see an option to add a list format that does not make them into cards.
<img width="1471" alt="スクリーンショット 2024-03-21 13 42 50" src="https://github.com/aarongilly/obsidian-semantic-canvas-plugin/assets/90127278/9f56b64b-3574-4ded-9998-444cc95f0dd0">

**Comment by aarongilly** [comment]
so basically you'd like an option to exclude "aliases" from the generated Canvas? 
That seems pretty straightforward. I'll add it to my next "x.1" update.

**Comment by aarongilly** [comment]
Done! See the new option added with the update.
