### ISSUE TITLE
[FR] Automatically connect a dragged note onto canvas with pre-existing properties

### ISSUE THREAD

**Issue by djsudduth** [aarongilly/obsidian-semantic-canvas-plugin#3]
Hi!  Great plugin!  It would be great addition that when I drag an existing note that already had properties onto an existing canvas, the connections would happen automatically vs manually having to connect. I know I can do on the canvas back to the notes - but then the properties need adjusting.  Thanks!

**Comment by Faeust** [comment]
I like this, but only if it's togglable. Sometimes I have a lot of different connections and it's nice to be able to delete them after I do a bunch so I can see the canvas better, even though the properties stay as they are. A 'show/hide all connections' option would be good.

**Comment by aarongilly** [comment]
I like this idea too. I'll see what I can make happen when I get around to updating it.  I like that it stays pretty well within the lane of what this plugin is already doing, conceptually.

Full disclosure - I haven't touched the plugin since its original release and just noticed the **Issues** tab here in Github has some activity in it.

**Comment by aarongilly** [comment]
Okay I think I can do this in a manner of speaking. I will probably **not** do the "on drop" trigger, but instead I will add a right-click (or long-press, for mobile) menu item that gives you a pair of new functions:

1. Show existing connections
2. Pull note properties in to canvas

I can't figure out how to name them.  But #1 would only draw new edges to **already existing nodes** on the canvas, whereas option 2 would draw new edges AND populate new nodes for note properties that aren't already on the canvas.

**Comment by Faeust** [comment]
I think those terms/phrases work! Any news on whether this will be added in soon?

**Comment by aarongilly** [comment]
I've gotten sidetracked on my "main" coding project, but this one is next up. I don't anticipate getting this done before October, but it's a matter of "when", not "if". Sorry it's putting you in the waiting game.

**Comment by aarongilly** [comment]
Got this working tonight, along with some other new features. Will require a bit more testing, but should be released fairly soon.

**Comment by aarongilly** [comment]
Feature implemented. Go give it a shot!
