### ISSUE TITLE
Feature Request: List of properities to ignore

### ISSUE THREAD

**Issue by egauthier** [aarongilly/obsidian-semantic-canvas-plugin#6]
I've been using this for 5 minutes, and I see huge possibilities!  I'm going to put a couple of Feature Requests in here, and will seperate them into seperate notes.

Settings: list of properities to ignore when Pulling in properties from notes to canvas.

For example, all of my notes have a property `tags` which I don't necessarily want on the canvas.

**Comment by aarongilly** [comment]
"I've been using this for 5 minutes" - lol.

I'll look forward to your suggestions! And your first one here is an obvious "should have been here all along" suggestion. Great call. That'll be next up.

**Comment by aarongilly** [comment]
Done. Great suggestion. Should have been the way I went the first time.

**Comment by egauthier** [comment]
Thanks!  The more I was thinking about this, the logic may may run better the other way, or both.

So a list of properties to exclude, and/or a list of only properties to include.  In addition to the use case I posed with always wanting to exclude `tags` (for example, I can see folks want to include *only* properties `x`, `y` and `z`.

Kind of like the DENY_ALL _FROM / ALLOW_ALL_FROM logic used elsewhere.  I hope I'm explaining this well, and I know user documentation for this sort of inner / outer join logic can be a challenge.

**Comment by aarongilly** [comment]
Basically, a whitelist approach as an alternative to a blacklist approach. That makes sense. Technically it would be dead simple to switch from blacklist to whitelist, but including the option to use either would be a tiny bit more scaffolding than I have time for right now. I'll definitely add it on the v1.3 release at some point in the next half year or so. Thanks for the suggestions.
